language: elixir
elixir:
  - 1.6.1
otp_release:
  - 20.2
matrix:
  include:
  - otp_release: 18.3
    elixir: 1.4.5
  - otp_release: 19.3
    elixir: 1.5.3

env:
  - MIX_ENV=test

cache:
  directories:
    - deps
    - _build

script:
  - mix compile --warning-as-errors
  - if [ "$TRAVIS_ELIXIR_VERSION" == "1.6.0" ]; then mix format --check-formatted; fi
  - mix credo
  - mix test
